baseURL = 'https://danetyk.pl/'
title = 'danetyk.pl | Wszystko o danych'
description = "Wszytko o Data Science, Data Engineering i Data Analysis, czyli wszystko o przetwarzaniu, eksploracji, analizie i modelowaniu danych. W skr贸cie: wszystko o danetyce ;) | Data Science | Data Engineering | Data Analysis | Danetyka | Danologia | Python | SQL"
theme = "PaperMod"
paginate = 5
defaultContentLanguage = 'pl'
languageCode = 'pl_PL'

# Google Analytics 4
googleAnalyticsID = 'G-35NN9PBX18'

[[menu.main]]
name = 'Archiwum'
url = 'archives'

[[menu.main]]
name = 'Blog'
url = '/'

[[menu.main]]
name = 'Szukaj'
url = 'search/'

[[menu.main]]
identifier = 'Tagi'
name = 'Tagi'
url = 'tags'

[params.homeInfoParams]
Content = """
## O blogu 
Znajdziecie tutaj przede wszystkim artykuy zwizane w taki, czy inny spos贸b, z przetwarzaniem, analiz i modelowaniem
danych z wykorzystaniem najpopularniejszych w bran偶y technologii (np. Python, SQL).

&nbsp;

## Kontakt 
W sprawach wszelakich piszcie na **kontakt@danetyk.pl**.

&nbsp;

## Media spoecznociowe 
Zapraszam Was r贸wnie偶 na Facebooka, GitHuba, Kaggle'a i Discorda. Na Facebooku znajdziecie newsy dotyczce
funkcjonowania bloga. Na GitHubie znajdziecie artykuy w formie PDF, jak r贸wnie偶 kody 藕r贸dowe. Na Kaggle znajdziecie
zestawy danych i notebooki. Na Discordzie natomiast mo偶ecie rozmawia na temat wszystkiego tego, co teoretyczne i
praktyczne w danetyce.
"""

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/danetykpl"

[[params.socialIcons]]
name = "github"
url = "https://github.com/danetykpl"

[[params.socialIcons]]
name = "kaggle"
url = "https://www.kaggle.com/danetykpl"

[[params.socialIcons]]
name = "discord"
url = "https://discord.gg/sJbTqMsZEM"

[params]
ShowShareButtons = true
ShowReadingTime = true
dateFormat = "2 January 2006"
ShowPostNavLinks = true
ShowCodeCopyButtons = true
env = "production"
description = "Wszytko o Data Science, Data Engineering i Data Analysis, czyli wszystko o przetwarzaniu, eksploracji, analizie i modelowaniu danych. W skr贸cie: wszystko o danetyce ;) | Data Science | Data Engineering | Data Analysis | Danetyka | Danologia | Python | SQL"
keywords = "data science, data engineering, data analysis, danetyka, danetyk, danetyczka, danologia, danolog, analiza danych, przetwarzanie danych, modelowanie danych, dane, informacje, analityka, statystyka"

[outputs]
home = [ "HTML", "RSS", "JSON" ]
